//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiexamen.WSROkto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblExamen", Namespace="http://schemas.datacontract.org/2004/07/WsApiexamen")]
    [System.SerializableAttribute()]
    public partial class tblExamen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExamenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExamen {
            get {
                return this.idExamenField;
            }
            set {
                if ((this.idExamenField.Equals(value) != true)) {
                    this.idExamenField = value;
                    this.RaisePropertyChanged("idExamen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSROkto.IWSOkto")]
    public interface IWSOkto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/AgregarExamen", ReplyAction="http://tempuri.org/IWSOkto/AgregarExamenResponse")]
        string[] AgregarExamen(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/AgregarExamen", ReplyAction="http://tempuri.org/IWSOkto/AgregarExamenResponse")]
        System.Threading.Tasks.Task<string[]> AgregarExamenAsync(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/GetTblExamens", ReplyAction="http://tempuri.org/IWSOkto/GetTblExamensResponse")]
        apiexamen.WSROkto.tblExamen[] GetTblExamens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/GetTblExamens", ReplyAction="http://tempuri.org/IWSOkto/GetTblExamensResponse")]
        System.Threading.Tasks.Task<apiexamen.WSROkto.tblExamen[]> GetTblExamensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/ConsultarExamen", ReplyAction="http://tempuri.org/IWSOkto/ConsultarExamenResponse")]
        apiexamen.WSROkto.tblExamen[] ConsultarExamen(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/ConsultarExamen", ReplyAction="http://tempuri.org/IWSOkto/ConsultarExamenResponse")]
        System.Threading.Tasks.Task<apiexamen.WSROkto.tblExamen[]> ConsultarExamenAsync(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/EliminarExamen", ReplyAction="http://tempuri.org/IWSOkto/EliminarExamenResponse")]
        string[] EliminarExamen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/EliminarExamen", ReplyAction="http://tempuri.org/IWSOkto/EliminarExamenResponse")]
        System.Threading.Tasks.Task<string[]> EliminarExamenAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/ActualizarExamen", ReplyAction="http://tempuri.org/IWSOkto/ActualizarExamenResponse")]
        string[] ActualizarExamen(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/ActualizarExamen", ReplyAction="http://tempuri.org/IWSOkto/ActualizarExamenResponse")]
        System.Threading.Tasks.Task<string[]> ActualizarExamenAsync(int id, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/ConsultarExamenbyId", ReplyAction="http://tempuri.org/IWSOkto/ConsultarExamenbyIdResponse")]
        apiexamen.WSROkto.tblExamen[] ConsultarExamenbyId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSOkto/ConsultarExamenbyId", ReplyAction="http://tempuri.org/IWSOkto/ConsultarExamenbyIdResponse")]
        System.Threading.Tasks.Task<apiexamen.WSROkto.tblExamen[]> ConsultarExamenbyIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSOktoChannel : apiexamen.WSROkto.IWSOkto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOktoClient : System.ServiceModel.ClientBase<apiexamen.WSROkto.IWSOkto>, apiexamen.WSROkto.IWSOkto {
        
        public WSOktoClient() {
        }
        
        public WSOktoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOktoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOktoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOktoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] AgregarExamen(int id, string Nombre, string Descripcion) {
            return base.Channel.AgregarExamen(id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarExamenAsync(int id, string Nombre, string Descripcion) {
            return base.Channel.AgregarExamenAsync(id, Nombre, Descripcion);
        }
        
        public apiexamen.WSROkto.tblExamen[] GetTblExamens() {
            return base.Channel.GetTblExamens();
        }
        
        public System.Threading.Tasks.Task<apiexamen.WSROkto.tblExamen[]> GetTblExamensAsync() {
            return base.Channel.GetTblExamensAsync();
        }
        
        public apiexamen.WSROkto.tblExamen[] ConsultarExamen(int id, string Nombre, string Descripcion) {
            return base.Channel.ConsultarExamen(id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<apiexamen.WSROkto.tblExamen[]> ConsultarExamenAsync(int id, string Nombre, string Descripcion) {
            return base.Channel.ConsultarExamenAsync(id, Nombre, Descripcion);
        }
        
        public string[] EliminarExamen(int id) {
            return base.Channel.EliminarExamen(id);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarExamenAsync(int id) {
            return base.Channel.EliminarExamenAsync(id);
        }
        
        public string[] ActualizarExamen(int id, string Nombre, string Descripcion) {
            return base.Channel.ActualizarExamen(id, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarExamenAsync(int id, string Nombre, string Descripcion) {
            return base.Channel.ActualizarExamenAsync(id, Nombre, Descripcion);
        }
        
        public apiexamen.WSROkto.tblExamen[] ConsultarExamenbyId(int id) {
            return base.Channel.ConsultarExamenbyId(id);
        }
        
        public System.Threading.Tasks.Task<apiexamen.WSROkto.tblExamen[]> ConsultarExamenbyIdAsync(int id) {
            return base.Channel.ConsultarExamenbyIdAsync(id);
        }

        internal object ConsultarExamen(int id)
        {
            throw new NotImplementedException();
        }
    }
}
